name: sass-boiler-plate

services:
  postgres:
    image: postgres:18
    container_name: sass-boiler-plate-postgres
    environment:
      POSTGRES_DB: sass-boiler-plate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sass-boiler-plate_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sass-boiler-plate_postgres_data:
